spring:
  cloud:
    gateway:
      routes:
        - id: parkingspace_route
          uri: lb://tueparking-parkingspace
          predicates:
            - Path=/api/parkingspace/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

#        - id: member_route
#          uri: lb://tueparking-member
#          predicates:
#            - Path=/api/member/**
#          filters:
#            - RewritePath=/api(?<segment>/?.*), $\{segment}

        - id: login_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast$\{segment}


